wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703169783.429471
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.11.2
      5: 0.16.1
      8:
      - 5
      10:
      - 9
      13: darwin-arm64
