wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703177553.44203
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.11.2
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 15
