wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: DNN
dataset:
  desc: null
  value: Custom
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703108329.646735
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      4: 3.11.2
      5: 0.16.1
      8:
      - 4
      - 5
      10:
      - 9
      13: darwin-arm64
